### ISSUE TITLE
RC3 Version of Jsonapi

### ISSUE THREAD

**Issue by jthoms1** [EarthlingInteractive/laravel-jsonapi#1]
Update code to produce JSON that matches the current spec of jsonapi.org.

**Comment by jpchip** [comment]
Thanks, I saw that the RC3 canidate had been released already. It will probably be a few weeks before I have any time to spend on this project again. Updating to RC3 will introduce breaking changes to the API, so I want to make sure I have the time to update the test cases and test thoroughly myself. Thanks for your input though!

**Comment by jthoms1** [comment]
We will be making this change in a fork. Will then provide a pull request.

**Comment by jpchip** [comment]
Published release v5.0.0, which produces JSON that matches jsonapi 1.0.0.rc3 specs.
